"""Add foreign keys on units_hierarchy

Revision ID: 1f0047479a82
Revises: 430813b0434d
Create Date: 2022-06-22 17:23:07.103170

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f0047479a82"
down_revision = "430813b0434d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk__units_hierarchy__parent_id__shop_units"),
        "units_hierarchy",
        "shop_units",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk__units_hierarchy__id__shop_units"), "units_hierarchy", "shop_units", ["id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk__units_hierarchy__id__shop_units"), "units_hierarchy", type_="foreignkey")
    op.drop_constraint(op.f("fk__units_hierarchy__parent_id__shop_units"), "units_hierarchy", type_="foreignkey")
    # ### end Alembic commands ###
