"""Add category_info table

Revision ID: 4b1034d5040c
Revises: 1f0047479a82
Create Date: 2022-06-22 17:26:39.696736

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b1034d5040c"
down_revision = "430813b0434d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_info",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("sum", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["shop_units.id"], name=op.f("fk__category_info__id__shop_units"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__category_info")),
    )
    op.create_index(op.f("ix__category_info__id"), "category_info", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__category_info__id"), table_name="category_info")
    op.drop_table("category_info")
    # ### end Alembic commands ###
