"""Add UnitHierarchy table

Revision ID: 4cdc399aff5e
Revises: c11b6527acbf
Create Date: 2022-06-15 09:14:08.782872

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4cdc399aff5e"
down_revision = "c11b6527acbf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "units_hierarchy",
        sa.Column("parent_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
    )
    op.create_index(op.f("ix__units_hierarchy__id"), "units_hierarchy", ["id"], unique=False)
    op.create_index(op.f("ix__units_hierarchy__parent_id"), "units_hierarchy", ["parent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__units_hierarchy__parent_id"), table_name="units_hierarchy")
    op.drop_index(op.f("ix__units_hierarchy__id"), table_name="units_hierarchy")
    op.drop_table("units_hierarchy")
    # ### end Alembic commands ###
