"""empty message

Revision ID: 694a46a124cd
Revises: 372ff9de02ad
Create Date: 2022-06-25 21:41:47.454952

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "694a46a124cd"
down_revision = "372ff9de02ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS ltree")
    op.add_column("shop_units", sa.Column("path", sqlalchemy_utils.types.ltree.LtreeType(), nullable=False))
    op.create_index("ix_shop_units_path", "shop_units", ["path"], unique=False, postgresql_using="gist")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS ltree")
    op.drop_index("ix_shop_units_path", table_name="shop_units", postgresql_using="gist")
    op.drop_column("shop_units", "path")
    # ### end Alembic commands ###
