"""Add last_update field to category_info

Revision ID: f664e1e54e38
Revises: 372ff9de02ad
Create Date: 2022-06-26 19:25:48.389707

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f664e1e54e38"
down_revision = "372ff9de02ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("category_info", sa.Column("last_update", sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category_info", "last_update")
    # ### end Alembic commands ###
